name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ApeWorX/github-action@v1
      with:
        python-version: 3.9

    - name: Compile contracts
      run: ape compile --size

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Run tests
      env:
          WEB3_INFURA_PROJECT_ID: f8b4d65ef4634cb7a3e1af5bf8d53ec1        
      run: ape test -s
      timeout-minutes: 10
